# Generated by Django 5.1.3 on 2024-11-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesVendedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='empresa',
            new_name='rut',
        ),
    ]
