# Generated by Django 5.1.3 on 2024-11-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesVendedor', '0002_rename_empresa_cliente_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_a_pagar',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
