# Generated by Django 5.1.3 on 2024-11-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesVendedor', '0005_rename_cantidadproducto_pedido_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='direccionCliente',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fecha_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccionCliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
    ]
