# Generated by Django 5.1.3 on 2024-12-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesVendedor', '0007_pedido_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor',
        ),
    ]
