# Generated by Django 5.1.3 on 2024-12-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesVendedor', '0011_repartidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='user',
        ),
    ]
