# Generated by Django 5.1.3 on 2024-12-01 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesVendedor', '0012_remove_repartidor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudesVendedor.repartidor'),
        ),
    ]
